export const environment = {
  production: true,
  //url: 'http://192.168.73.100:3000',

  authServiceBaseUrl: 'http://192.168.0.110:8080',
  authApiGetUsersOperation: '/users/',
  authApiBaseUserOperation: '/user/',
  authApiUpdatePasswordOperation: '/user/updatePassword/',
  authApiRegisterUserOperation: '/register/',
  authApiRegisterAgenteOperation: '/registerAgente/',
  authApiGetRolesOperation: '/roles/',
  authApiGetPerfilesOperation: '/profiles',
  authApiGetPerfilOperation: '/profile/',
  authApiGetTokenOperation: '/token/generate-token',
  authApiGetUsersByRoleOperation: '/users:listByRole',
  // Endpoints para Gestión de Operaciones de Negocio
  coreServiceBaseUrl: 'http://192.168.0.110:8081',
  // -> Empresa
  coreApiBaseEmpresaOperation: '/empresa',
  coreApiFilterEmpresaOperation: '/filter',
  coreApiGetConfiguracionEmpresaOperation: '/configuracion',
  coreApiGetFormularioEmpresaOperation: '/formulario',
  // -> Agentes
  coreApiBaseAgenteOperation: '/agente',
  coreApiBaseEmpresaGerenteOperation: ':listEmpresaGerente',
  coreApiBaseAllGerenteOperation: ':listAllGerente',
  coreApiRegisterBaseAgenteOperation: '/register',
  coreApiSetEmpresaToAgenteOperation: '/setEmpresa',
  coreApiGetAgenteConfigOperation: '/_config',
  coreApiGetAgenteEmailConfigOperation: '/_emailConfig',
  coreApiGetAgenteConfigTables: '/preferenciaDeTabla/agentes',
  coreApiGetConfigTables: '/preferenciaDeTabla',
  coreApiUpdateConfigTables: '/updtPreferenciaDeTabla',
  coreApiGetConfigTableName: '/agentes',
  coreApiBaseAgenteOperationList: '/list/page',
  coreApiBatchDeleteAgenteOperation: ':batchDelete',
  coreApiBatchUpdateRolAgenteOperation: ':batchRoles/',
  coreApiBatchDeleteUserAgenteOperation: ':batchDisableGerente',
  //  -> Clientes
  coreApiBaseClienteOperation: '/cliente',
  coreApiGetClientesListOperation: ':listByEmpresa',
  coreApiRegisterEventoClienteOperation: '/evento',
  coreApiGetEventosClienteOperation: ':listEvents',
  coreApiBatchDeleteClienteOperation: ':batchDelete',
  // ->CheckIn
  coreApiBaseCheckInOperation: '/visita',
  //  -> Servicios Tecnico
  coreApiBaseServicioTecnicoOperation: '/servicioTecnico',
  coreApiBatchDeleteServicioTecnicoOperation: ':batchDelete',
  coreApiGetServiciosTecnicosListOperation: ':listByEmpresa',
  coreApiArchivosServicioTecnicoOperation: '/archivo',
  coreApiArchivosServicioTecnicoAgente: '/agenteServicioTecnico',
  // Endpoints para Catálogos
  coreApiBatchDeleteUsuariosOperation: ':batchDelete',
  //Endpoints para Catálogos
  coreApiGetActividadEconomicaCatalog: '/actividadEconomica/list',
  coreApiGetRegimenFiscalCatalog: '/regimenFiscal/list',
  coreApiGetCodigoPostalCatalog: '/codigoPostal/filter',
  coreApiBaseTipoDeServicioCatalog: '/tipoDeServicio',
  coreApiGetTipoDeServicioCatalog: ':listByEmpresa',
  coreApiBaseSerieCotizacionCatalog: '/serie-cotizacion',
  coreApiDisableSerieCotizacionByEmpresaCatalog: '/_disable',
  coreApiGetSerieCotizacionByEmpresaCatalog: '/_list-by-empresa',
  coreApiGetSerieCotizacionByEmpresaAndActivesCatalog: '/_list-by-empresa-actives',
  coreApiBaseTipoCotizacionCatalog: '/tipo-cotizacion',
  coreApiDisableTipoCotizacionByEmpresaCatalog: '/_disable',
  coreApiGetTipoCotizacionByEmpresaCatalog: '/_list-by-empresa',
  coreApiGetTipoCotizacionByEmpresaAndActivesCatalog: '/_list-by-empresa-actives',
  coreApiBaseVigenciaCotizacionCatalog: '/vigencia-cotizacion',
  coreApiDisableVigenciaCotizacionByEmpresaCatalog: '/_disable',
  coreApiGetVigenciaCotizacionByEmpresaCatalog: '/_list-by-empresa',
  coreApiGetVigenciaCotizacionByEmpresaAndActivesCatalog: '/_list-by-empresa-actives',
  //  -> Productos
  coreApiBaseProductoOperation: '/producto',
  coreApiGetProductosListOperation: '/:list',
  coreApiBatchDeleteProductoOperation: ':batchDelete',
  coreApiGetCodigoProductoCatalog: '/filter',
  //  -> Cotizaciones
  coreApiBaseCotizacionOperation: '/cotizacion',
  coreApiGetCotizacionListOperation: '/:list',
  coreApiBatchDeleteCotizacionOperation: ':batchDelete',
  coreApiBatchDeleteLogicCotizacionOperation: ':batchDeleteLogic',
  coreApiGetCodigoCotizacionCatalog: '/filter',
  googleMapsKey: 'AIzaSyAYCA8FtUjOYaBcwY50oaNoZquwAGm97mo',

  formsServiceBaseUrl: 'http://192.168.0.110:8082',
 // formularios
  //  -> Productos
  formsApiBaseFormularioOperation: '/formulario',
  formsApiGetFormularioListOperation: '/:list',
  formsApiBatchDeleteFormularioOperation: ':batchDelete',
  formsApiGetCodigoFormularioCatalog: '/filter'
};
